/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ndk1_Simple5 */

#ifndef _Included_ndk1_Simple5
#define _Included_ndk1_Simple5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk1_Simple5
 * Method:    callGetUuid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk1_Simple5_callGetUuid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
